### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by vordemann** [icebreaker-science/frontend#15]
If a device is available, then the user should be able to click on the corresponding institution in the availability section of the wiki page (https://github.com/icebreaker-science/frontend/issues/13) and a contact form will open.
This form consists of the following entries:

- [x] Name

- [x] Email

- [x]  Message

- [x] Submit Button

The contact request is then send to the server via API call https://github.com/icebreaker-science/backend/issues/17 and after a successful response the user is redirected back to the corresponding wiki page ( = the contact form closes)

**Comment by benjiWdev** [comment]
waiting on icebreaker-science/backend#17 to be merged for testing

**Comment by benjiWdev** [comment]
branch /feature/contact-form
