### ISSUE TITLE
Make website usable in Safari

### ISSUE THREAD

**Issue by vordemann** [icebreaker-science/frontend#28]
Site does not work in the Safari Browser.

**Comment by dajenet** [comment]
What does not work for you? For me everything seems to work fine on Safari.

**Comment by bieniusa** [comment]
We only see an empty page that does not show anything. Waiting does not help, in contrast to Google Chrome where the network appears in << 1 min.

**Comment by chaoran-chen** [comment]
Are there error messages in the browser console?

**Comment by bieniusa** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/437744/92415862-2008ff80-f15b-11ea-8f29-8a1fa78aeb14.png">

Hope you can read it...
The issue also appears on the other subpages, not just network.

**Comment by chaoran-chen** [comment]
[1] presents a possible solution and [2] gives an explanation but the error is really weird since there are no cross-origin requests..

[1] https://stackoverflow.com/a/58832120/8376759
[2] https://stackoverflow.com/a/56755581/8376759

**Comment by vordemann** [comment]
![Bildschirmfoto 2020-09-14 um 22 55 52](https://user-images.githubusercontent.com/25126755/93137288-80f58200-f6dd-11ea-95a0-01c37649fe34.png)

There is still an issue in safari regarding the login functionality. Tested on the same account in Chrome and Safari. In Chrome login succeeded whereas in Safari the server is returning a 401

**Comment by chaoran-chen** [comment]
This is weird. Could you please provide more information regarding the connection such as the request and response headers?

**Comment by vordemann** [comment]
Now it works again, weirtd
