### ISSUE TITLE
Integrate design concept

### ISSUE THREAD

**Issue by vordemann** [icebreaker-science/frontend#36]
This issue requires collaboration with @FrEy0 who has created a design with color schemes and fonts for the webpage. Implement the design concept into the frontend.

**Comment by vordemann** [comment]
Also add content to the landing page within this isse

**Comment by benjiWdev** [comment]
Navigation done, closing #40 with this issue.

**Comment by benjiWdev** [comment]
landing page done.

**Comment by benjiWdev** [comment]
login and signup done, creaeting pull request
