### ISSUE TITLE
Image upload for wiki pages

### ISSUE THREAD

**Issue by vordemann** [icebreaker-science/frontend#37]
This is the frontend counterpart issue to https://github.com/icebreaker-science/backend/issues/35
The user should be able to upload an image, when creating a new wiki page (for now only devices).
However, this is not a mandatory field in the form.

**Comment by vordemann** [comment]
@chaoran-chen Only the person who is creating the page should be able to add a picture? What if several users add availability and like to show a pic alongside their device. Is the backend running some form of authentification on the request?

**Comment by chaoran-chen** [comment]
Hmm. The question is whether a picture should belong to the device or to the device-availability. For simplicity, I have currently defined that only a device can own a single picture which can only be uploaded during the initial creation of the device.
