### ISSUE TITLE
Frontend New Design Feedback Ticket

### ISSUE THREAD

**Issue by vordemann** [icebreaker-science/frontend#46]
Please leave your comments and remarks regarding the new design ticket here.

**Comment by chaoran-chen** [comment]
- Everything seems a little too big. Maybe use a normal font size for the "normal" texts? (approx. 16px instead of 30px?)
- And maybe, also decrease the rounding a bit?

**Comment by dajenet** [comment]
- The header image is very large and so the navigation bar is not on top.

**Comment by chaoran-chen** [comment]
Everything in this issue is resolved :)
