### ISSUE TITLE
Design changes to Edit device availability popup

### ISSUE THREAD

**Issue by vordemann** [icebreaker-science/frontend#91]
Popup is too large on some devices.

**Comment by benjiWdev** [comment]
The Popup should be scrollable. Maybe prevent scrolling in the background while the popup is active to make it easier

**Comment by alasmaleki** [comment]
This issue is affecting all of the modals (contact, edit-delete and add availability), and the behavior only happens when using Firefox. Since the same code is also used in #86 I will commit the fix there.

**Comment by alasmaleki** [comment]
fixed by the last commit in #86
